### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sylvestreee** [sylvestreee/Prog3D#1]
# Fonctionnalités

- [x] Exagérer les distances via le clavier
- [ ] Éclairer avec soleil
- [x] Varier l'écoulement du temps 
- [x] Rajouter la lune
- [ ] Rajouter la ceinture de Saturne 
- [ ] Rajouter la ceinture d'astéroïdes
- [x] Rajouter les axes circulaires
- [ ] Ajouter des textes d'informations pour chaque planète / astre
